import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import Navbar from "./Navbar/page";
import Footer from "./Footer/page";
import Provider from "./Providers/page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Provider>
          <div className="max-w-[1600px] w-full mx-auto px-4 md:px-8 lg:px-12">
            <Navbar></Navbar>
            <main>{children}</main>
          </div>

          <ToastContainer position="top-center" autoClose={3000} />

          <Footer></Footer>
        </Provider>
      </body>
    </html >
  );
}